sudo: required

language: python

services: 
  - docker

python:
  - '2.7'
  - '3.5'

before_script:
  - docker run --name elastic -d -p 9200:9200 elasticsearch:2.4

script:
  - pip install coveralls
  - make coverage
  - make check-examples
  - make integration
  - make benchmark

after_script:
  - docker stop elastic
  - docker rm elastic

after_success:
  - coveralls
